"""
Quick test script to verify reports functionality and check who Sarah is.
"""
from database.db import SessionLocal
from database.models import Report, Investigator

db = SessionLocal()

print("=" * 60)
print("REPORTS IN DATABASE")
print("=" * 60)
reports = db.query(Report).all()
for r in reports:
    print(f"\nReport ID: {r.report_id}")
    print(f"  Type: {r.report_type}")
    print(f"  Date: {r.generated_date}")
    print(f"  File Path: {r.file_path}")
    print(f"  Generated By ID: {r.generated_by}")
    
    # Get investigator name
    investigator = db.query(Investigator).filter(
        Investigator.investigator_id == r.generated_by
    ).first()
    if investigator:
        print(f"  Generated By: {investigator.name} ({investigator.email})")
        print(f"  Designation: {investigator.designation}")

print("\n" + "=" * 60)
print("ALL INVESTIGATORS")
print("=" * 60)
investigators = db.query(Investigator).all()
for inv in investigators:
    print(f"\n{inv.name}")
    print(f"  Email: {inv.email}")
    print(f"  Designation: {inv.designation}")
    print(f"  ID: {inv.investigator_id}")

db.close()

print("\n" + "=" * 60)
print("TO TEST REPORTS:")
print("=" * 60)
print("1. Make sure backend server is running")
print("2. Login as investigator (sarah.ahmed@university.edu / password123)")
print("3. Go to Reports page in investigator portal")
print("4. You should see 4 reports generated by Dr. Sarah Ahmed")
print("5. Click Download to test file download")
print("=" * 60)

